-- ============================================================
-- Riley Security — Neon SQL Migration
-- Run this in Neon SQL Editor: console.neon.tech
-- ============================================================

-- 1. agent_runs — tracks each Tier 1 autonomous sweep run
CREATE TABLE IF NOT EXISTS agent_runs (
  id                SERIAL PRIMARY KEY,
  status            TEXT    NOT NULL DEFAULT 'running',   -- 'running' | 'completed' | 'failed'
  alerts_processed  INTEGER NOT NULL DEFAULT 0,
  true_positives    INTEGER NOT NULL DEFAULT 0,
  false_positives   INTEGER NOT NULL DEFAULT 0,
  skipped           INTEGER NOT NULL DEFAULT 0,
  duration_ms       INTEGER,
  error_message     TEXT,
  started_at        TIMESTAMP NOT NULL DEFAULT NOW(),
  completed_at      TIMESTAMP
);

-- 2. incidents — confirmed true positive incidents generated by Tier 1 agent
CREATE TABLE IF NOT EXISTS incidents (
  id                  SERIAL PRIMARY KEY,
  alert_id            INTEGER NOT NULL REFERENCES alerts(id),
  agent_run_id        INTEGER NOT NULL REFERENCES agent_runs(id),
  severity            TEXT    NOT NULL,                   -- 'low'|'medium'|'high'|'critical'
  title               TEXT    NOT NULL,
  threat_summary      TEXT    NOT NULL,
  affected_asset      TEXT    NOT NULL,
  mitre_tactic        TEXT,
  attack_vector       TEXT    NOT NULL,
  potential_impact    TEXT    NOT NULL,
  correlation_notes   TEXT    NOT NULL,
  analyst_rationale   TEXT    NOT NULL,
  remediation_runbook TEXT    NOT NULL,
  confidence          REAL    NOT NULL,                   -- 0.0–1.0
  incident_ref        TEXT    NOT NULL,                   -- 'INC-0001'
  created_at          TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 3. recon_scans — OSINT intelligence sweep results
CREATE TABLE IF NOT EXISTS recon_scans (
  id                SERIAL PRIMARY KEY,
  target            TEXT    NOT NULL,
  target_type       TEXT    NOT NULL,                     -- 'ip'|'domain'|'hash'|'url'
  status            TEXT    NOT NULL DEFAULT 'running',   -- 'running'|'completed'|'failed'
  osint_data        JSONB,
  threat_summary    TEXT,
  risk_score        REAL,                                 -- 0–100
  risk_level        TEXT,                                 -- 'low'|'medium'|'high'|'critical'
  iocs              JSONB,                                -- string[]
  mitre_techniques  JSONB,                                -- string[]
  recommendations   TEXT,
  analyst_rationale TEXT,
  error_message     TEXT,
  duration_ms       REAL,
  created_at        TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 4. waitlist — email capture for paid tier signups
CREATE TABLE IF NOT EXISTS waitlist (
  id         SERIAL PRIMARY KEY,
  email      TEXT NOT NULL UNIQUE,
  plan       TEXT NOT NULL DEFAULT 'pro',
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
